FROM bladedisc/bladedisc:latest-devel-cuda11.0
ARG PYTORCH_COMMIT=""
ENV PYTORCH_COMMIT=${PYTORCH_COMMIT}

COPY ./scripts /opt/scripts
RUN apt-get update -y && \
    apt-get install -y clang-8 clang++-8 python3.8 python3.8-dev && \
    rm /usr/bin/python && \
    ln -s /usr/bin/python3.8 /usr/bin/python && \
    python -m pip install --upgrade pip && \
    python -m pip install cpython pyyaml typing_extensions virtualenv numpy torchvision
RUN python -m pip uninstall torch && \
    python -m pip install https://bladedisc-ci.oss-cn-hongkong.aliyuncs.com/download/torch-ltc/torch-1.12.0a0%2Bgitd9896b8-cp38-cp38-linux_x86_64.whl