FROM bladedisc/bladedisc:latest-devel-cuda11.0
ARG PYTORCH_COMMIT=""
ENV PYTORCH_COMMIT=${PYTORCH_COMMIT}

COPY ./scripts /opt/scripts
RUN apt-get update -y && \
    apt-get install -y clang-8 clang++-8 python3.8 python3.8-dev && \
    rm /usr/bin/python && \
    ln -s /usr/bin/python3.8 /usr/bin/python && \
    python -m pip install pyyaml typing_extensions virtualenv numpy
RUN bash /opt/scripts/install-pytorch-ltc.sh