config_setting(
    name = "is_platform_alibaba",
    define_values = {"is_platform_alibaba": "true"},
)

config_setting(
    name = "is_patine",
    define_values = {"is_patine": "true"},
)

config_setting(
    name = "is_blade_gemm",
    define_values = {"is_blade_gemm": "true"},
)

config_setting(
    name = "is_mkldnn",
    define_values = {"is_mkldnn": "true"},
)

config_setting(
    name = "disc_aarch64",
    define_values = {"disc_aarch64": "true"},
)

config_setting(
    name = "disc_x86",
    define_values = {"disc_x86": "true"},
)

config_setting(
    name = "is_torch_disc",
    define_values = {"is_torch_disc": "true"},
)

config_setting(
    name = "is_tf_serving",
    define_values = {"is_tf_serving": "true"},
)
