repos:
- repo: local
  hooks:
  - id: copyright_checker
    name: copyright_checker
    entry: python ./scripts/pre-commit/copyright.py
    language: system
    files: \.(cc|cpp|h|py|sh)$
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v10.0.1
  hooks:
  - id: clang-format
    name: clang-format

