load("@com_google_protobuf//:protobuf.bzl", "cc_proto_library")

cc_proto_library(
    name = "compile_metadata_bridge",
    srcs = ["compile_metadata.proto"],
    visibility = ["//visibility:public"],
)
