load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "tf_test_common",
    srcs = [
        "tf_test_common.py",
    ],
    deps = [
        "//tf_blade/util:tf_import_helper",
    ],
    visibility = ["//visibility:public"],
)
