workspace(name = "disc_compiler")

local_repository(
    name = "org_tensorflow",
    path = "../tf_community",
)

# Initialize the TensorFlow repository and all dependencies.
#
# The cascade of load() statements and tf_workspace?() calls works around the
# restriction that load() statements need to be at the top of .bzl files.
# E.g. we can not retrieve a new repository with http_archive and then load()
# a macro from that repository in the same file.
load("@org_tensorflow//tensorflow:workspace3.bzl", "tf_workspace3")

tf_workspace3()

load("@org_tensorflow//tensorflow:workspace2.bzl", "tf_workspace2")

tf_workspace2()

load("@org_tensorflow//tensorflow:workspace1.bzl", "tf_workspace1")

tf_workspace1()

load("@org_tensorflow//tensorflow:workspace0.bzl", "tf_workspace0")

tf_workspace0()

load("@org_tensorflow//third_party:repo.bzl", "tf_http_archive", "tf_mirror_urls")

tf_http_archive(
    name = "iree-dialects",
    sha256 = "f6ed70146b85d27c25cb4653cfb879d7954be426516b1cac230cbf5bb8b041da",
    strip_prefix = "iree-7cd0a8cb6e1027188faa75b9361c4b10aab4707c/llvm-external-projects/iree-dialects",
    urls = tf_mirror_urls("https://github.com/iree-org/iree/archive/7cd0a8cb6e1027188faa75b9361c4b10aab4707c.zip"),
    patch_file = ["@disc_compiler//third_party/iree:StructuredTransformOpsExt.cpp.patch"],
)
