workspace(name = "org_torch_blade")


load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.4.0/rules_python-0.4.0.tar.gz",
        "https://github.com/bazelbuild/rules_python/releases/download/0.4.2/rules_python-0.4.0.tar.gz",
    ],
)

#`pybind11_bazel`
# See https://github.com/pybind/pybind11_bazel
git_repository(
  name = "pybind11_bazel",
  remote = "https://github.com/pybind/pybind11_bazel.git",
  commit = "26973c0ff320cb4b39e45bc3e4297b82bc3a6c09",
)

load("//bazel/torch:.torch_env_workspace.bzl", "torch_env_workspace")
torch_env_workspace()

load("//bazel/torch:.torch_env_workspace.bzl", "torch_pybind11_dir")
# We still require the pybind library.
new_local_repository(
  name = "pybind11",
  build_file = "@pybind11_bazel//:pybind11.BUILD",
  path = torch_pybind11_dir()
)

http_archive(
    name = "googltest",
    sha256 = "bc1cc26d1120f5a7e9eb450751c0b24160734e46a02823a573f3c6b6c0a574a7",
    strip_prefix = "googletest-e2c06aa2497e330bab1c1a03d02f7c5096eb5b0b",
    urls = [
        "http://pai-blade.oss-cn-zhangjiakou.aliyuncs.com/build_deps/googletest/e2c06aa2497e330bab1c1a03d02f7c5096eb5b0b.zip",
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/googletest/archive/e2c06aa2497e330bab1c1a03d02f7c5096eb5b0b.zip",
        "https://github.com/google/googletest/archive/e2c06aa2497e330bab1c1a03d02f7c5096eb5b0b.zip",
    ],
)

http_archive(
    name = "bazel_skylib",
    sha256 = "1c531376ac7e5a180e0237938a2536de0c54d93f5c278634818e0efc952dd56c",
    urls = [
        "http://pai-blade.oss-cn-zhangjiakou.aliyuncs.com/build_deps/bazel-skylib-1.0.3.tar.gz",
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
    ],
)

http_archive(
    name = "rules_foreign_cc",
    sha256 = "33a5690733c5cc2ede39cb62ebf89e751f2448e27f20c8b2fbbc7d136b166804",
    strip_prefix = "rules_foreign_cc-0.5.1",
    urls = [
        "http://pai-blade.oss-cn-zhangjiakou.aliyuncs.com/build_deps/rules_foreign_cc/0.5.1.tar.gz",
        "https://github.com/bazelbuild/rules_foreign_cc/archive/0.5.1.tar.gz",
    ],
)

http_archive(
    name = "go_sdk",
    sha256 = "33a5690733c5cc2ede39cb62ebf89e751f2448e27f20c8b2fbbc7d136b166804",
    strip_prefix = "rules_foreign_cc-0.5.1",
    urls = [
        "https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz",
    ],
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

local_repository(
    name = "org_tensorflow",
    path = "../tf_community",
)

local_repository(
    name = "org_mhlo_builder",
    path = "../mhlo_builder",
)
# Initialize TensorFlow's external dependencies.
load("@org_tensorflow//tensorflow:workspace3.bzl", "tf_workspace3")
tf_workspace3()

load("@org_tensorflow//tensorflow:workspace2.bzl", "tf_workspace2")
tf_workspace2()

load("@org_tensorflow//tensorflow:workspace1.bzl", "tf_workspace1")
tf_workspace1()

load("@pybind11_bazel//:python_configure.bzl", "python_configure")
python_configure(name = "local_config_python") #, python_interpreter_target = "@python_interpreter//:python_bin")

bind(
    name = "python_headers",
    actual = "@local_config_python//:python_headers",
)

