--- 
backend: 
  - all
input: 
  input0: 
    - 1
    - 1
    - 64
    - 320
  num_inputs: 1
model: 
  filename: models/crnn.jit.pt
  name: crnn
runtime: 
  device: 0
  precision: 
    - fp32
    - fp16
