--- 
backend: 
  - all
input: 
  input0: 
    - 1
    - 3
    - 640
    - 640
  num_inputs: 1
model: 
  filename: models/yolov5.jit.pt
  name: yolov5
runtime: 
  device: 0
  precision: 
    - fp32
    - fp16
