package(default_visibility = ["//visibility:public"])

filegroup(
    name = "torch_blade_py_srcs",
    srcs = [
        "//src/compiler/jit:torch_blade_jit_py_srcs",
        "//src/compiler/mlir:torch_blade_mlir_py_srcs",]
)

filegroup(
    name = "torch_blade_py_hdrs",
    srcs = [
        "//src/compiler/jit:torch_blade_jit_py_hdrs",
        "//src/compiler/mlir:torch_blade_mlir_py_hdrs",]
)
