load("//src/custom_ops:build_defs.bzl", "tf_blade_ops_py_tests")

tf_blade_ops_py_tests(
    srcs = [
        "bilstm_op_test.py",
        "fused_lstm_element_wise_op_test.py",
    ],
    tags = ["gpu"],
)
