name: Cronjobs

# Add cronjob later
# Use workflow dispatch to manual trigger the job for now
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *' # every hours
  workflow_dispatch:

jobs:
  DummyTestJob:
    uses: ./.github/workflows/reusable.yml
    with:
      name: dummy_test_job
      base_image: bladedisc/bladedisc:latest-runtime-torch1.12.0-cu113
      device: gpu-t4
      dockerfile: docker/cronjobs/Dockerfile.dummy
      exec_command: python3 -c 'import torch; print(torch.__config__.show())'
      push_command: source scripts/ci/deploy_docker.sh && push_images
      remote_dev_docker: ""
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 
