name: Cronjobs

# Add cronjob later
# Use workflow dispatch to manual trigger the job for now
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 23 * * *' # 11:30 pm
  workflow_dispatch:

jobs:
  NGC-TorchTRT-D2:
    if: github.event.schedule != '30 23 * * *'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-trt-and-d2-benchmark
      base_image: nvcr.io/nvidia/pytorch:22.06-py3
      device: gpu-t4
      dockerfile: docker/cronjobs/Dockerfile.torch.ngc
      exec_command: cd pytorch_blade && bash ./benchmark/run_benchmark.sh
      push_command: source scripts/ci/deploy_docker.sh && push_images
      remote_dev_docker: bladedisc:disc-dev-pt-ngc
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 
