name: Cronjobs

on:
  schedule:
    - cron: '30 23 * * *' # 11:30 pm
    - cron: '0/2 * * * *' # every 2 minutes

jobs:
  DummyTestJob:
    if: github.event.schedule != '0/2 * * * *'
    uses: ./.github/workflows/reusable_cronjob.yml
    with:
      name: dummy_test_job
      base_image: bladedisc:latest-runtime-torch1.12.0-cu113
      device: gpu-t4
      dockerfile: docker/cronjobs/Dockerfile.dummy
      exec_command: python3 -c 'import torch; print(torch.__config__.show())'
      push_command: source scripts/ci/deploy_docker.sh && push_images
      remote_dev_docker: ""
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 
