name: pytorch1_7_1-cuda11_0
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 17 * * *' # 1:00 am UTC+8
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/resuable_gpu_build.yml
    with:
      cuda_version: cu110
      remote_runtime_docker: bladedisc:latest-runtime-torch1.7.1-cu110
      develop_base_image: nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04
      runtime_base_image: nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04
      extra_envs: -e TORCH_BLADE_BUILD_TENSORRT_STATIC=ON
          -e TORCH_BLADE_CI_BUILD_TORCH_VERSION=1.7.1+cu110
      exec_command: bash ./scripts/ci/test_pytorch_blade.sh
      deploy_command: TORCH_VERSION=1.7.1+cu110 bash ./scripts/ci/deploy_pytorch_blade.sh
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
