name: tf2_8-yitian
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 17 * * *' # 1:00 am UTC+8:00
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'alibaba/BladeDISC'
    # The type of runner that the job will run on
    runs-on: [self-hosted, yitian-ci]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Build Dev Docker
      run: |
        set -e
        source $HOME/.cache/proxy_config
        git submodule sync
        git submodule update --depth=1 --init --recursive
        cp /etc/apt/sources.list .
        docker build -t disc-dev-cpu-yitian \
          --build-arg BASEIMAGE=ubuntu:20.04 \
          --build-arg DISC_HOST_TF_VERSION="tensorflow-aarch64==2.8" \
          -f docker/dev/Dockerfile.aarch64 .
    - name: Build And Test DISC
      run: |
        set -e
        docker run --rm -t --user $(id -u):$(id -g) \
          -v $HOME/.cache:$HOME/.cache \
          -v /etc/passwd:/etc/passwd:ro \
          -v /etc/group:/etc/group:ro \
          -v /etc/hosts:/etc/hosts:ro \
          -v $PWD:/disc \
          -e GITHUB_WORKFLOW=$GITHUB_WORKFLOW \
          -h=`hostname` \
          -w /disc \
          disc-dev-cpu-yitian \
          bash ./scripts/ci/build_and_test.sh --cpu-only --target_cpu_arch="armv8.6-a-sve2"
    - name: Deploy Dev Docker Image
      if: github.event.ref == 'refs/heads/main'
      env:
        ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GITHUB_PULL_REQUEST: ${{ github.event.number }}
        LOCAL_DEV_DOCKER: disc-dev-cpu-yitian
        REMOTE_DEV_DOCKER: bladedisc:latest-devel-cpu-yitian
      run: |
        set -e
        echo "Try to deploy runtime docker image..."
        source $HOME/.cache/proxy_config
        bash ./scripts/ci/deploy_wrapper.sh
    - name: Deploy Runtime Docker Image
      if: github.event.ref == 'refs/heads/main'
      env:
        ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GITHUB_PULL_REQUEST: ${{ github.event.number }}
        RUNTIME_BASEIMAGE: bladedisc/bladedisc:latest-devel-cpu-yitian
        RUNTIME_DOCKER_FILE: docker/runtime/Dockerfile.tf.aarch64
        REMOTE_RUNTIME_DOCKER: bladedisc:latest-runtime-tensorflow2.8-cpu-yitian
      run: |
        set -e
        echo "Try to deploy runtime docker image..."
        source $HOME/.cache/proxy_config
        bash ./scripts/ci/deploy_wrapper.sh
