name: tf2_8-cuda11_3
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 17 * * *' # 1:00 am UTC+8:00
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/resuable_gpu_build.yml
    with:
      cuda_version: cu113
      runner_tag: gpu-a10
      remote_runtime_docker: bladedisc:latest-runtime-tensorflow2.8
      develop_base_image: nvidia/cuda:11.3.0-cudnn8-devel-ubuntu18.04
      runtime_base_image: tensorflow/tensorflow:2.8.0-gpu
      extra_build_args: --build-arg PYTHON_VERSION=PYTHON3.8 --build-arg DISC_HOST_TF_VERSION="tensorflow-gpu==2.8" --build-arg ENABLE_FIND_FASTEST_APT_SOURCE=OFF
      exec_command: bash ./scripts/ci/build_and_test.sh
      tf_blade_command: bash ./scripts/ci/test_tensorflow_blade.sh cu113 2.8
      deploy_command: bash ./scripts/ci/deploy_tensorflow_blade.sh
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
