name: TorchBenchCPU

# Add cronjob later
# Use workflow dispatch to manual trigger the job for now
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 15 * * *' # 11:30 pm UTC+8:00
    - cron: '30 15 * * 5' # 11:30 pm UTC+8:00 every Friday
  workflow_dispatch:

jobs:
  TorchBenchIntelTiny-131:
    if: github.event.schedule != '30 15 * * 5' # daily or dispatch
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu
      device: g7-bench
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh X86-intel tiny 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchCpuPartial-131:
    if: github.event.schedule == '30 15 * * *'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu
      device: g7-bench
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh X86-intel partial 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchIntelFull-131:
    if: github.event.schedule == '30 15 * * 5'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu
      device: g7-bench
      timeout_minutes: 10080 # 7 days
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh X86-intel full 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchIntelFull-200:
    if: github.event.schedule == '30 15 * * 5'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch-2.0.0-cpu
      device: g7-bench
      timeout_minutes: 10080 # 7 days
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh X86-intel full 200
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchYitianTiny-131:
    if: github.event.schedule != '30 15 * * 5' # daily or dispatch
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu-yitian
      device: yitian-bench-sh2
      proxy_config: source ~/.cache/proxy_config
      dockerfile: docker/cronjobs/Dockerfile.torch.bench.aarch64
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh AArch64-yitian tiny 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchYitianPartial-131:
    if: github.event.schedule == '30 15 * * *'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu-yitian
      device: yitian-bench-sh2
      proxy_config: source ~/.cache/proxy_config
      dockerfile: docker/cronjobs/Dockerfile.torch.bench.aarch64
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh AArch64-yitian partial 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchYitianFull-131:
    if: github.event.schedule == '30 15 * * 5'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu-yitian
      device: yitian-bench-sh2
      timeout_minutes: 14400 # 10 days
      proxy_config: source ~/.cache/proxy_config
      dockerfile: docker/cronjobs/Dockerfile.torch.bench.aarch64
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh AArch64-yitian full 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchYitianAMPTiny-131:
    if: github.event.schedule != '30 15 * * 5' # daily or dispatch
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu-yitian
      device: yitian-bench
      proxy_config: source ~/.cache/proxy_config
      dockerfile: docker/cronjobs/Dockerfile.torch.bench.aarch64
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh AArch64-yitian-amp tiny 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchYitianAMPPartial-131:
    if: github.event.schedule == '30 15 * * *'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu-yitian
      device: yitian-bench
      proxy_config: source ~/.cache/proxy_config
      dockerfile: docker/cronjobs/Dockerfile.torch.bench.aarch64
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh AArch64-yitian-amp partial 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit
 
  TorchBenchYitianAMPFull-131:
    if: github.event.schedule == '30 15 * * 5'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu-yitian
      device: yitian-bench
      timeout_minutes: 14400 # 10 days
      proxy_config: source ~/.cache/proxy_config
      dockerfile: docker/cronjobs/Dockerfile.torch.bench.aarch64
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh AArch64-yitian-amp full 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchYitianAMPFull-200:
    if: github.event.schedule == '30 15 * * 5'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch2.0.0-cpu-yitian
      device: yitian-bench
      timeout_minutes: 14400 # 10 days
      proxy_config: source ~/.cache/proxy_config
      dockerfile: docker/cronjobs/Dockerfile.torch.bench.aarch64
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh AArch64-yitian-amp full 200
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit
 
  TorchBenchG6RFull-131:
    if: github.event.schedule == '30 15 * * 5'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu-aarch64
      device: g6r-bench
      timeout_minutes: 14400 # 10 days
      dockerfile: docker/cronjobs/Dockerfile.torch.bench.aarch64
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh AArch64-g6r full 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchAMDFull-131:
    if: github.event.schedule == '30 15 * * 5'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu
      device: g7a-bench
      timeout_minutes: 10080 # 7 days
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench_cpu.sh X86-amd full 131
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit
