load("//tests:build_defs.bzl", "tf_blade_ops_py_tests")

tf_blade_ops_py_tests(
    srcs = [
        "non_max_suppression_op_test.py",
    ],
    deps = [
        "//:context",
    ],
    tags = ["gpu"],
)
